-- SCRIPT DE CRIAÇÃO E CORREÇÃO DE TABELAS (ATELIER)
-- Execute este script no SQL Editor do Supabase.

-- ==========================================
-- 1. TABELAS EXISTENTES (Garantir que existem com as colunas corretas)
-- ==========================================

CREATE TABLE IF NOT EXISTS public.pedidos (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    nome TEXT,
    data_pedido DATE,
    data_entrega DATE,
    status TEXT DEFAULT 'pendente',
    itens JSONB,
    data_real DATE,
    preco_total NUMERIC,
    email_cliente TEXT,
    cupao_codigo TEXT,
    desconto_percent INT4,
    preco_final NUMERIC,
    valor_adiantado NUMERIC DEFAULT 0,
    pagamentos JSONB DEFAULT '[]'::jsonb,
    fatura_simples_link TEXT,
    fatura_final_link TEXT,
    fatura_pagina_fisica TEXT,
    fatura_quer_receber BOOLEAN DEFAULT false,
    fatura_metodo_envio TEXT,
    fatura_contato_envio TEXT,
    fatura_status_envio TEXT,
    fatura_data_emissao TIMESTAMPTZ,
    fatura_valor_total NUMERIC,
    fatura_codigo TEXT
);

-- Garante que colunas adicionadas posteriormente existem, caso a tabela já estivesse criada
ALTER TABLE public.pedidos ADD COLUMN IF NOT EXISTS fatura_simples_link TEXT;
ALTER TABLE public.pedidos ADD COLUMN IF NOT EXISTS fatura_final_link TEXT;
ALTER TABLE public.pedidos ADD COLUMN IF NOT EXISTS fatura_pagina_fisica TEXT;
ALTER TABLE public.pedidos ADD COLUMN IF NOT EXISTS fatura_quer_receber BOOLEAN DEFAULT false;
ALTER TABLE public.pedidos ADD COLUMN IF NOT EXISTS fatura_metodo_envio TEXT;
ALTER TABLE public.pedidos ADD COLUMN IF NOT EXISTS fatura_contato_envio TEXT;
ALTER TABLE public.pedidos ADD COLUMN IF NOT EXISTS fatura_status_envio TEXT;
ALTER TABLE public.pedidos ADD COLUMN IF NOT EXISTS fatura_data_emissao TIMESTAMPTZ;
ALTER TABLE public.pedidos ADD COLUMN IF NOT EXISTS fatura_valor_total NUMERIC;
ALTER TABLE public.pedidos ADD COLUMN IF NOT EXISTS fatura_codigo TEXT;

CREATE TABLE IF NOT EXISTS public.alocacoes (
    id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_pote TEXT,
    percentagem NUMERIC
);

CREATE TABLE IF NOT EXISTS public.tipos_itens (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    nome TEXT,
    dias INT4 DEFAULT 3,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Tags/categorias para os Gastos do Dia na página Contas (ex: Materiais, Transporte...)
CREATE TABLE IF NOT EXISTS public.tags_gastos (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    nome TEXT NOT NULL,
    criado_em TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.transacoes (
    id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT now(),
    data DATE,
    descricao TEXT,
    valor NUMERIC,
    fluxo TEXT,
    tipo TEXT
);

CREATE TABLE IF NOT EXISTS public.vouchers (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    codigo TEXT,
    nome_cliente TEXT,
    numero_cliente TEXT,
    email_cliente TEXT,
    data_validade DATE,
    vitalicio BOOLEAN DEFAULT false,
    estado TEXT DEFAULT 'disponivel',
    data_estado_muda TIMESTAMPTZ,
    criado_em TIMESTAMPTZ DEFAULT now(),
    desconto_percent INT4
);

-- ==========================================
-- 2. NOVAS TABELAS PARA O MÓDULO DE FINANÇAS
-- ==========================================

-- Tabela para guardar os dados fiscais dos clientes
CREATE TABLE IF NOT EXISTS public.clientes_financas (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    nome TEXT NOT NULL,
    nif TEXT UNIQUE,
    email TEXT,
    morada TEXT,
    telefone TEXT,
    criado_em TIMESTAMPTZ DEFAULT now()
);

-- Tabela para registar faturas associadas aos pedidos
CREATE TABLE IF NOT EXISTS public.faturas (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    numero_fatura TEXT UNIQUE,
    cliente_id UUID REFERENCES public.clientes_financas(id) ON DELETE SET NULL,
    pedido_id UUID REFERENCES public.pedidos(id) ON DELETE SET NULL,
    valor_total NUMERIC NOT NULL,
    data_emissao DATE DEFAULT CURRENT_DATE,
    estado TEXT DEFAULT 'pendente', -- Ex: pendente, emitida, paga, cancelada
    criado_em TIMESTAMPTZ DEFAULT now()
);

COMMENT ON TABLE public.clientes_financas IS 'Registo de clientes para efeitos de faturação e NIF';
COMMENT ON TABLE public.faturas IS 'Registo de faturas emitidas associadas a clientes e pedidos';

-- ==========================================
-- 3. CONTAS DE ADMINISTRAÇÃO E ACESSOS
-- ==========================================

-- Ativar a extensão pgcrypto para permitir a encriptação de senhas nativa no PostgreSQL
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Tabela para contas de administração
CREATE TABLE IF NOT EXISTS public.contas_adm (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    nome TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    senha TEXT NOT NULL,
    tipo_utilizador TEXT NOT NULL DEFAULT 'admin',
    criado_em TIMESTAMPTZ DEFAULT now()
);

-- Inserir o primeiro utilizador com privilégios máximos (senha encriptada)
-- O Supabase usa a extensão pgcrypto (crypt e gen_salt) para armazenar de forma segura.
INSERT INTO public.contas_adm (nome, email, senha, tipo_utilizador)
VALUES (
    'Rodrigo Almeida Ribeiro',
    'rodrigo.el.atelie@gmail.com',
    crypt('27249199r', gen_salt('bf')),
    'maximo'
)
ON CONFLICT (email) DO NOTHING;

COMMENT ON TABLE public.contas_adm IS 'Registo de utilizadores administrativos (nome, email, tipo e senha encriptada)';

-- ==========================================
-- 4. FUNÇÃO DE LOGIN SEGURO PARA A TABELA PERSONALIZADA
-- ==========================================
CREATE OR REPLACE FUNCTION public.login_adm(p_email TEXT, p_senha TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_user public.contas_adm;
BEGIN
    -- Procurar o utilizador pelo email e verificar se a senha encriptada coincide
    SELECT * INTO v_user
    FROM public.contas_adm
    WHERE email = p_email AND senha = crypt(p_senha, senha);

    IF v_user.id IS NOT NULL THEN
        RETURN jsonb_build_object('sucesso', true, 'nome', v_user.nome, 'tipo', v_user.tipo_utilizador, 'email', v_user.email);
    ELSE
        RETURN jsonb_build_object('sucesso', false);
    END IF;
END;
$$;

-- ==========================================
-- 5. FUNÇÕES CRUD PARA GESTÃO DE UTILIZADORES
-- ==========================================

-- A0) Listar Utilizadores (SECURITY DEFINER para contornar RLS)
CREATE OR REPLACE FUNCTION public.listar_adm()
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN (
        SELECT COALESCE(jsonb_agg(
            jsonb_build_object(
                'id', id,
                'nome', nome,
                'email', email,
                'tipo_utilizador', tipo_utilizador,
                'gestor_contas', gestor_contas,
                'criado_em', criado_em
            ) ORDER BY criado_em
        ), '[]'::jsonb)
        FROM public.contas_adm
    );
END;
$$;

-- A1) Alterar Senha com verificação da senha atual
CREATE OR REPLACE FUNCTION public.alterar_senha_adm(p_id UUID, p_senha_atual TEXT, p_senha_nova TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_user public.contas_adm;
BEGIN
    SELECT * INTO v_user FROM public.contas_adm
    WHERE id = p_id AND senha = crypt(p_senha_atual, senha);

    IF v_user.id IS NULL THEN
        RETURN jsonb_build_object('sucesso', false, 'mensagem', 'Senha atual incorreta');
    END IF;

    UPDATE public.contas_adm
    SET senha = crypt(p_senha_nova, gen_salt('bf'))
    WHERE id = p_id;

    RETURN jsonb_build_object('sucesso', true, 'mensagem', 'Senha alterada com sucesso');
END;
$$;

-- A) Criar Utilizador
CREATE OR REPLACE FUNCTION public.criar_adm(p_nome TEXT, p_email TEXT, p_senha TEXT, p_tipo TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    INSERT INTO public.contas_adm (nome, email, senha, tipo_utilizador)
    VALUES (p_nome, p_email, crypt(p_senha, gen_salt('bf')), p_tipo);
    
    RETURN jsonb_build_object('sucesso', true, 'mensagem', 'Utilizador criado com sucesso');
EXCEPTION WHEN OTHERS THEN
    RETURN jsonb_build_object('sucesso', false, 'mensagem', SQLERRM);
END;
$$;

-- B) Atualizar Utilizador
CREATE OR REPLACE FUNCTION public.atualizar_adm(p_id UUID, p_nome TEXT, p_email TEXT, p_senha TEXT, p_tipo TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    IF p_senha IS NULL OR p_senha = '' THEN
        -- Atualiza sem mexer na senha
        UPDATE public.contas_adm
        SET nome = p_nome, email = p_email, tipo_utilizador = p_tipo
        WHERE id = p_id;
    ELSE
        -- Atualiza tudo, incluindo senha encriptada
        UPDATE public.contas_adm
        SET nome = p_nome, email = p_email, tipo_utilizador = p_tipo, senha = crypt(p_senha, gen_salt('bf'))
        WHERE id = p_id;
    END IF;

    RETURN jsonb_build_object('sucesso', true, 'mensagem', 'Utilizador atualizado com sucesso');
EXCEPTION WHEN OTHERS THEN
    RETURN jsonb_build_object('sucesso', false, 'mensagem', SQLERRM);
END;
$$;

-- C) Apagar Utilizador
CREATE OR REPLACE FUNCTION public.apagar_adm(p_id UUID)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    DELETE FROM public.contas_adm WHERE id = p_id;
    RETURN jsonb_build_object('sucesso', true, 'mensagem', 'Utilizador apagado com sucesso');
EXCEPTION WHEN OTHERS THEN
    RETURN jsonb_build_object('sucesso', false, 'mensagem', SQLERRM);
END;
$$;

-- ==========================================
-- 5b. GESTOR DE CONTAS ÚNICO (acesso exclusivo à página Contas)
-- Só um utilizador de cada vez pode ter este papel. Para passar
-- o papel a outro utilizador é preciso confirmar a senha de quem
-- é gestor actualmente.
-- ==========================================

ALTER TABLE public.contas_adm ADD COLUMN IF NOT EXISTS gestor_contas BOOLEAN NOT NULL DEFAULT false;

CREATE UNIQUE INDEX IF NOT EXISTS idx_unico_gestor_contas
    ON public.contas_adm (gestor_contas)
    WHERE gestor_contas = true;

-- Usado pelo gate da página Contas: confirma se o email já com sessão iniciada é o gestor actual
CREATE OR REPLACE FUNCTION public.sou_gestor_contas(p_email TEXT)
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
AS $$
    SELECT EXISTS (
        SELECT 1 FROM public.contas_adm
        WHERE email = p_email AND gestor_contas = true
    );
$$;

-- Transfere o papel de gestor de contas para outro utilizador.
-- Exige a senha de quem detém o papel actualmente (excepto se ainda não houver nenhum gestor definido).
CREATE OR REPLACE FUNCTION public.definir_gestor_contas(p_novo_id UUID, p_senha_atual_gestor TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_atual public.contas_adm;
BEGIN
    SELECT * INTO v_atual FROM public.contas_adm WHERE gestor_contas = true LIMIT 1;

    IF v_atual.id IS NOT NULL THEN
        IF v_atual.id = p_novo_id THEN
            RETURN jsonb_build_object('sucesso', false, 'mensagem', 'Este utilizador já é o gestor de contas.');
        END IF;

        IF v_atual.senha <> crypt(COALESCE(p_senha_atual_gestor, ''), v_atual.senha) THEN
            RETURN jsonb_build_object('sucesso', false, 'mensagem', 'Senha do gestor de contas actual incorrecta.');
        END IF;

        UPDATE public.contas_adm SET gestor_contas = false WHERE id = v_atual.id;
    END IF;

    UPDATE public.contas_adm SET gestor_contas = true WHERE id = p_novo_id;

    RETURN jsonb_build_object('sucesso', true, 'mensagem', 'Gestor de contas actualizado com sucesso.');
END;
$$;

-- ==========================================
-- 6. REGISTAR CLIENTES PARA FINANÇAS AUTOMATICAMENTE
-- ==========================================

CREATE OR REPLACE FUNCTION public.registar_cliente_financas(p_nome TEXT, p_email TEXT, p_nif TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_id UUID;
    v_nif_real TEXT := NULLIF(TRIM(p_nif), '');
    v_email_real TEXT := NULLIF(TRIM(p_email), '');
BEGIN
    -- Se o NIF foi fornecido, procurar por ele primeiro
    IF v_nif_real IS NOT NULL THEN
        SELECT id INTO v_id FROM public.clientes_financas WHERE nif = v_nif_real LIMIT 1;
        
        IF v_id IS NOT NULL THEN
            -- Atualiza nome e email do cliente existente
            UPDATE public.clientes_financas 
            SET nome = p_nome, email = COALESCE(v_email_real, email)
            WHERE id = v_id;
            RETURN jsonb_build_object('sucesso', true, 'id', v_id);
        END IF;
    END IF;

    -- Se não achou por NIF, procurar por email
    IF v_email_real IS NOT NULL THEN
        SELECT id INTO v_id FROM public.clientes_financas WHERE email = v_email_real LIMIT 1;
        
        IF v_id IS NOT NULL THEN
            -- Atualiza o NIF (se não tinha) e o nome
            UPDATE public.clientes_financas 
            SET nome = p_nome, nif = COALESCE(v_nif_real, nif)
            WHERE id = v_id;
            RETURN jsonb_build_object('sucesso', true, 'id', v_id);
        END IF;
    END IF;

    -- Se não encontrou de forma alguma, cria novo
    INSERT INTO public.clientes_financas (nome, email, nif)
    VALUES (p_nome, v_email_real, v_nif_real)
    RETURNING id INTO v_id;

    RETURN jsonb_build_object('sucesso', true, 'id', v_id);
EXCEPTION WHEN OTHERS THEN
    RETURN jsonb_build_object('sucesso', false, 'erro', SQLERRM);
END;
$$;

-- ==========================================
-- 7. MIGRAÇÃO DE CLIENTES ANTIGOS PARA FINANÇAS
-- ==========================================
-- Este bloco insere automaticamente qualquer cliente que esteja nos pedidos mas não em clientes_financas
INSERT INTO public.clientes_financas (nome, email)
SELECT DISTINCT TRIM(p.nome), TRIM(p.email_cliente)
FROM public.pedidos p
WHERE p.nome IS NOT NULL AND p.nome != ''
  AND NOT EXISTS (
      SELECT 1 FROM public.clientes_financas c 
      WHERE LOWER(c.nome) = LOWER(TRIM(p.nome)) 
         OR (p.email_cliente IS NOT NULL AND LOWER(c.email) = LOWER(TRIM(p.email_cliente)))
  );

-- ==========================================
-- 8. TABELA DE FATURAS INDEPENDENTE E MIGRAÇÃO
-- ==========================================

CREATE TABLE IF NOT EXISTS public.faturas (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY
);

ALTER TABLE public.faturas ADD COLUMN IF NOT EXISTS pedido_id UUID;
ALTER TABLE public.faturas ADD COLUMN IF NOT EXISTS nome_cliente TEXT;
ALTER TABLE public.faturas ADD COLUMN IF NOT EXISTS nif TEXT;
ALTER TABLE public.faturas ADD COLUMN IF NOT EXISTS data_emissao TIMESTAMPTZ;
ALTER TABLE public.faturas ADD COLUMN IF NOT EXISTS valor_total NUMERIC;
ALTER TABLE public.faturas ADD COLUMN IF NOT EXISTS fatura_codigo TEXT;
ALTER TABLE public.faturas ADD COLUMN IF NOT EXISTS simples_link TEXT;
ALTER TABLE public.faturas ADD COLUMN IF NOT EXISTS final_link TEXT;
ALTER TABLE public.faturas ADD COLUMN IF NOT EXISTS pagina_fisica TEXT;
ALTER TABLE public.faturas ADD COLUMN IF NOT EXISTS quer_receber BOOLEAN DEFAULT false;
ALTER TABLE public.faturas ADD COLUMN IF NOT EXISTS metodo_envio TEXT;
ALTER TABLE public.faturas ADD COLUMN IF NOT EXISTS contato_envio TEXT;
ALTER TABLE public.faturas ADD COLUMN IF NOT EXISTS status_envio TEXT;

-- Desativa RLS para evitar bloqueios de segurança caso a tabela tenha sido criada manualmente no Supabase
ALTER TABLE public.faturas DISABLE ROW LEVEL SECURITY;

-- Migração de faturas antigas que estavam nos "pedidos" para a nova tabela
INSERT INTO public.faturas (
    pedido_id, nome_cliente, nif, data_emissao, valor_total, fatura_codigo, 
    simples_link, final_link, pagina_fisica, quer_receber, metodo_envio, contato_envio, status_envio
)
SELECT 
    p.id as pedido_id, 
    p.nome as nome_cliente,
    COALESCE((SELECT c.nif FROM public.clientes_financas c WHERE LOWER(c.nome) = LOWER(TRIM(p.nome)) LIMIT 1), '999999990') as nif,
    COALESCE(p.fatura_data_emissao, p.data_real::TIMESTAMPTZ, CURRENT_TIMESTAMP) as data_emissao,
    p.fatura_valor_total as valor_total,
    p.fatura_codigo,
    p.fatura_simples_link as simples_link,
    p.fatura_final_link as final_link,
    p.fatura_pagina_fisica as pagina_fisica,
    p.fatura_quer_receber as quer_receber,
    p.fatura_metodo_envio as metodo_envio,
    p.fatura_contato_envio as contato_envio,
    p.fatura_status_envio as status_envio
FROM public.pedidos p
WHERE (p.fatura_simples_link IS NOT NULL OR p.fatura_final_link IS NOT NULL)
  AND NOT EXISTS (
      SELECT 1 FROM public.faturas f WHERE f.pedido_id = p.id
  );

-- (Fim do script)

